version: '3'

services:
  frontend:
    build: ./frontend
    container_name: kaf305-web
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:3001
    restart: unless-stopped
    networks:
      - kaf305-network
    depends_on:
      - api


  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3001
      VUE_APP_SCHEDULE_API_KEY: SECRET_KEY
    ports:
      - "3001:3001"
    container_name: kaf305-api
    networks:
      - kaf305-network

  postgres:
    image: postgres:10.4
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    container_name: kaf305-db
    networks:
      - kaf305-network

  nginx:
    image: nginx:stable-alpine
    container_name: kaf305-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
    networks:
      - kaf305-network

volumes:
  postgres:
  api:

networks:
  kaf305-network:
    driver: bridge