version: '3'

services:
  frontend:
    build: ./frontend
    container_name: kaf305-web
    command: npm run start
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - kaf305-network

  api:
    build: ./api
    container_name: kaf305-api
    command: npm start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=localhost:3001
    depends_on:
      - postgres
    networks:
      - kaf305-network    

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "kaf305_api"
      POSTGRES_USER: "kaf305_api"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: kaf305-db
    networks:
      - kaf305-network

  nginx:
    image: nginx:stable-alpine
    container_name: realworld-docker-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
    networks:
      - kaf305-network

volumes:
  postgres:

networks:
  kaf305-network:
    driver: bridge